version: "3.9"  # optional since v1.27.0
services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - "postgres.env"
    volumes:
      - .docker-volume/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
